pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh 'docker build -t shazam-api services/shazam-api'
      }
    }
    stage('Push') {
      steps {
        sh 'docker push <dockerhub>/shazam-api'
      }
    }
    stage('Deploy') {
      steps {
        sh 'kubectl apply -f k8s/'
      }
    }
  }
}
